id: opecha:P001722
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10590
  title: སུམ་རྟགས་འགྲེལ་པ་ལེགས་བཤད་སྣང་བྱེད་ནོར་བུ་དང་སྐད་གཉིས་སྦྱོར་ཚུལ་ཀུན་གསལ་མེ་ལོང་དང་གཟུངས་སྔགས་ཀློག་འདོན་ལེགས་སྦྱར་སྨྲ་བའི་ཉིན་བྱེད་སོགས།
  volume: ''
  author: ''
