id: P001722
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10590
  title: སུམ་རྟགས་འགྲེལ་པ་ལེགས་བཤད་སྣང་བྱེད་ནོར་བུ་དང་སྐད་གཉིས་སྦྱོར་ཚུལ་ཀུན་གསལ་མེ་ལོང་དང་གཟུངས་སྔགས་ཀློག་འདོན་ལེགས་སྦྱར་སྨྲ་བའི་ཉིན་བྱེད་སོགས།
  author: ''
  volumes:
    4702dae7e3094f12a1ca02fb88d8f4e0:
      image_group_id: I1KG10592
      title: ''
      volume_number: 1
      total_pages: 474
