id: I405F4DDE
legacy_id: P001722
ocr_import_info:
  bdrc_scan_id: W1KG10590
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T13:07:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:46:45.819081+00:00'
last_modified: 2022-08-31 10:47:20.046153
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10590
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10590
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སུམ་རྟགས་འགྲེལ་པ་ལེགས་བཤད་སྣང་བྱེད་ནོར་བུ་དང་སྐད་གཉིས་སྦྱོར་ཚུལ་ཀུན་གསལ་མེ་ལོང་དང་གཟུངས་སྔགས་ཀློག་འདོན་ལེགས་སྦྱར་སྨྲ་བའི་ཉིན་བྱེད་སོགས།
  author: རྣམ་གླིང་པཎ་ཆེན་དཀོན་མཆོག་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.6685943187899568
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I1KG10592:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10592
      total_pages: 474
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10592.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6685943187899568
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
